on: push
name: Auto Test Run Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          # SLACK_CHANNEL: #karan ku
          SLACK_MESSAGE: 'Auto Test Run Started :rocket:'
        uses: rtCamp/action-slack-notify@v2
